---

- name: pingmachine
  hosts: wordpress
  become: yes
  tasks:
    - name: ping_machine_cible
      ping:
#php
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'
      ignore_errors: true

    - name: Install PHP
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-fpm
        - php-mysql
        - php-xml
    - name: Remove apache2
      package:
        name: apache2
        state: absent
#mysql
    - name: Install mysql
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python-mysql

    - name: Generate new root password
      command: openssl rand -hex 7
      args:
        creates: /root/.my.cnf

    - name: Remove anonymous users
      mysql_user:
        name: ""
        state: absent
      when: mysql_new_root_pass.changed

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
      when: mysql_new_root_pass.changed

    - name: Output new root password
      debug:
        msg: "New root password is {{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed
      
    - name: Update root password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_new_root_pass.stdout }}"
      loop:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      when: mysql_new_root_pass.changed

    - name: Create my.cnf.j2
      template:
        src: templates/mysql/my.cnf.j2
        dest: /root/.my.cnf
      when: mysql_new_root_pass.changed

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: Create nginx config
      template:
        src: template/nginx/default.j2
        dest: /etc/nginx/sites-available/default
