---

- name: pingmachine
  hosts: wordpress
  become: yes
  tasks:
    - name: ping_machine_cible
      ping:
# TOOLS
    - name: Install required tools
      apt:
        name:
          - unzip
        state: present
#php
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'
      ignore_errors: true

    - name: Install PHP
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-fpm
        - php-mysql
        - php-xml
    - name: Remove apache2
      package:
        name: apache2
        state: absent
#mysql
    - name: Install mysql
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python-mysqldb

    - name: temporisation
      pause:
        minutes: 2

    - name: Generate new root password
      command: openssl rand -hex 7
      args:
        creates: /root/.my.cnf
      register: mysql_new_root_pass

    - name: Remove anonymous users
      mysql_user:
        name: ""
        state: absent
      when: mysql_new_root_pass.changed

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
      when: mysql_new_root_pass.changed

    - name: Output new root password
      debug:
        msg: "New root password is {{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed

    - name: Update root password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_new_root_pass.stdout }}"
      loop:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      when: mysql_new_root_pass.changed

    - name: Create my.cnf.j2
      template:
        src: template/mysql/my.cnf.j2
        dest: /root/.my.cnf
      when: mysql_new_root_pass.changed

    - name: Create mysqld.cnf
      template:
        src: template/mysql/mysqld.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      when: mysql_new_root_pass.changed
      notify: restart mysql

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: Check PHP version
      command: php --version
      register: php_version
    - set_fact:
        fpm_sock: /run/php/php7.{{ php_version.stdout.split(" ")[1].split(".")[1] }}-fpm.sock
      when: ansible_distribution == 'Ubuntu'

    - name: Create nginx config
      template:
        src: template/nginx/default.j2
        dest: /etc/nginx/sites-available/default

    # WordPress
    - name: Unzip WordPress
      unarchive:
        src: files/wordpress-5.3.2-fr_FR.zip
        dest: /tmp
        creates: /tmp/wordpress/wp-settings.php

    - name: Create project folder
      file:
        dest: /var/www/book.example.com
        state: directory

    - name: Copy WordPress files
      command: cp -a /tmp/wordpress/. /var/www/book.example.com
      args:
        creates: /var/www/book.example.com/wp-settings.php

    - name: Create WordPress MySQL database
      mysql_db:
        name: wordpress
        state: present

    - name: Create WordPress MySQL user
      mysql_user:
        name: wordpress
        host: localhost
        password: bananas
        priv: wordpress.*:ALL

    - name: Create wp-config
      template:
        src: template/wordpress/wp-config.php.j2
        dest: /var/www/book.example.com/wp-config.php

    - name: Does the database exist?
      command: mysql -u root wordpress -e "SELECT ID FROM wordpress.wp_users LIMIT 1;"
      register: db_exist
      ignore_errors: true

    - name: Copy WordPress DB
      copy:
        src: template/wordpress/wp-database.sql
        dest: /tmp/wp-database.sql
      when: db_exist.rc > 0

    - name: Import WordPress DB
      mysql_db:
        target: /tmp/wp-database.sql
        state: import
        name: wordpress
      when: db_exist.rc > 0

  handlers:
    - name: restart nginx
      service:
          name: nginx
          state: restarted

  handlers:
    - name: restart mysql
      service:
          name: mysql
          state: restarted
